version: "3.8"

include:
  - kafka-cluster.yml

services:
  email_service:
    build: ./
    command: ./bin/app
    networks:
      - kafka_network
    volumes:
      - ./docker/containers-configs/config.yml:/configs/config.yml
      - ./templates:/templates
    depends_on:
      - kafka
    environment:
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
